import {Song} from '../../shared/index';

export var SONGS: Song[] = [
  {
    "id": 0,
    "title": "Mecha",
    "subtitle": "Alas, this is filler",
    "artist": "Somebody Else",
    "genre": "Badumtss",
    "credit": "",
    "banner": {},
    "background": {},
    "cdtitle": "",
    "music": {},
    "offset": 0,
    "bpms": [120],
    "stops": [0],
    "samplestart": 0,
    "samplelength": 0,
    "displaybpm": "120",
    "selectable": true,
    "notes": {}
  },
  {
    "id": 1,
    "title": "Goin' Under",
    "subtitle": "",
    "artist": "NegaRen",
    "genre": "Raggacore",
    "credit": "",
    "banner": {},
    "background": {},
    "cdtitle": "",
    "music": {},
    "offset": 0,
    "bpms": [210],
    "stops": [0],
    "samplestart": 0,
    "samplelength": 0,
    "displaybpm": "210",
    "selectable": true,
    "notes": {}
  },
  {
    "id": 2,
    "title": "Mecha-Tribe Assault",
    "subtitle": "",
    "artist": "Kommisar",
    "genre": "",
    "credit": "",
    "banner": {},
    "background": {},
    "cdtitle": "",
    "music": {},
    "offset": 0,
    "bpms": [180],
    "stops": [0],
    "samplestart": 0,
    "samplelength": 0,
    "displaybpm": "180",
    "selectable": true,
    "notes": {}
  }
];
